<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category  RAG
 * @author    Netstarter Team contact@netstarter.com
 * @copyright Copyright © 2018 Netstarter Pty Ltd. (http://www.netstarter.com.au) All rights reserved.
 */

namespace LearnKo\ThirdKo\Block;


use Magento\Framework\View\Element\Template;

class OrderList extends \Magento\Framework\View\Element\Template
{
    protected  $layoutProcessors;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        array $layoutProcessors = [],
        array $data = [])
    {
        $this->layoutProcessors = $layoutProcessors;
        parent::__construct($context, $data);
    }

    public function getJsLayout()
    {
        return parent::getJsLayout(); // TODO: Change the autogenerated stub
    }

}