<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category  RAG 
 * @author    Netstarter Team contact@netstarter.com
 * @copyright Copyright © 2018 Netstarter Pty Ltd. (http://www.netstarter.com.au) All rights reserved.
 */
?>
<h1>This is the template for Second KO observable</h1>

<div id="booklists" data-bind="scope:'dyanamiclists'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#booklists": {
            "magentoui": {
               "components": {
                    "dyanamiclists": {
                        "component": "booklists"
                    }
                }
            }
        }
    }
    </script>
</div>