<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category  RAG 
 * @author    Netstarter Team contact@netstarter.com
 * @copyright Copyright © 2018 Netstarter Pty Ltd. (http://www.netstarter.com.au) All rights reserved.
 */
?>
<h1>This is the template for Second KO examples</h1>


<div id="ko-component"
     data-bind="scope: 'kocomponent'"
     data-mage-init='{"magentoui":{"components":{"kocomponent": {"component": "greetings"}}}}'>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>