<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category  RAG 
 * @author    Netstarter Team contact@netstarter.com
 * @copyright Copyright © 2018 Netstarter Pty Ltd. (http://www.netstarter.com.au) All rights reserved.
 */
?>
<h1>This is the template for First KO examples</h1>
<h4>How to declare JS </h4>




<h4>The first way is : </h4>



<script type="text/x-magento-init">
    {
        "*":
            {
            "LearnKo_FirstKo/js/firstko_wayone":
                {
                    "name": "Vasan"
                }
            }
    }
</script>

<h4>The second way is : </h4>
<div data-mage-init='{"waytwo": {"name": "Suresh"}}'>
Way Two
</div>